
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[25,)" #mandatory (24 is current forge version)
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/codeka/castawayterrain/issues"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId="castawayterrain"
version="${file.jarVersion}"
displayName="Castaway Terrain"
#updateJSONURL="https://github.com/codeka/castawayterrain/"
displayURL="https://github.com/codeka/castawayterrain/"
authors="Codeka"
description='''
Terrain generation mode for castaway. Generates an island surrounded by endless ocean. Wilson! Wiiiilson!!
'''
[[dependencies.examplemod]] #optional
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.2]"
    ordering="NONE"
    side="BOTH"